# Site settings
title: Amalgam of Random Things
header-img: img/home-bg.jpg
email: felancarlogarcia@gmail..com
copyright_name: Felan Carlo Garcia
description: "A Blog about my Data Science and IoT ramblings"
baseurl: "https://cadrev.github.io"
url: "https://cadrev.github.io"
twitter_username: cadrev
github_username:  cadrev
facebook_username:  felan.garcia
email_username:  felancarlogarcia@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
